### ISSUE TITLE
Comments from a read-through

### ISSUE THREAD

**Issue by katilp** [awesome-workshop/continuous-integration-deployment-gitlab#4]
I went through this lesson as I will work through the material that comes later and I wanted to get an idea of what the participants have gone through. It is really very nice. I understand that it is still in development but I'm however listing here some minor remarks that I made when working through the lesson, feel free to take them into account or not 😃 

- [x] The entry-page introduction starts with "You’ve have recently learned about CI/CD through GitHub and Travis CI". This is a probably a leftover from an earlier instance of this tutorial. This time it does not look to me that there is anything like that in the pre-workshop material

In 02-enter-sandman:
- [x] before the first python example, although obvious probably for almost all, you could add a short note that it is enough to type python on command line to get to that environment (and exit() to exit...) 
- [x] the example of setupATLAS gives me (as a CMS user)
```
bash-4.2$ setupATLAS || echo ignore setupATLAS
bash: setupATLAS: command not found
ignore setupATLAS
```
(whether that matters)

in 04-understanding-yaml:
- [x] Maybe, after "YAML is Yet Another Markup Language that is usually the modus operandi for CI systems." add a simple phrase that describes what it does in context of CI to motivate the reader to read through and also mention that they are use elsewhere as well
- [x] typo in "howver two spaces "
- [x] It would be useful to have a brief explanation of the scope of the listing (in YAML) below Scalars. Do I get it correctly that it is there to illustrate the syntax of different things in YAML? It would maybe be good to start with a typical example YAML file in the CI context.
- [x] the anchor stuff requires a bit of brain gymnastics (which is probably not a bad thing)

in 05-understanding-yaml-and-ci
- [x] aha 💡  , now comes the YAML file in the CI context which I was expecting. For my learning type, I would have preferred to start with this, but I understand that other people may prefer to have the generic YAML introduction before
- [x] analysisbase is not known to CMS people but it probably does not matter here
- [x] at the end: "The API for all GitLab CI/CD pipeline configurations" -> "The reference guide for all GitLab CI/CD pipeline configurations"?

07-hello-world-ci
- [x] for easier copy-pasting, please remove > at the beginnning of the lines
- [x] this is the first time I hear of "linter", maybe a brief explanation?
- [x] I must be missing something, I pushed the (empty-as-instructed) file into the repo but I do not see what is in the instructions but this:
![aw-add-ci](https://user-images.githubusercontent.com/5859918/74435102-feb19080-4e63-11ea-9fd4-f81d126acc16.JPG)
- [x] it looks as the CI does not run if the file is empty
- [x] Indeed, if I add the hello world example, it runs nicely and clicking on CI/CD Pipelines I see this:
![aw-pipelines](https://user-images.githubusercontent.com/5859918/74437037-beeca800-4e67-11ea-860f-a9ba65d9c812.JPG)

More may follow...

**Comment by katilp** [comment]
in 08-adding-ci-to-your-code:
- [x] having done https://awesome-workshop.github.io/awesome-htautau-analysis/07-preparation/index.html and in my local `awesome-analysis-eventselection` on lxplus:
```
bash-4.2$ COMPILER=$(root-config --cxx)
bash-4.2$ $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx
skim.cxx:11:31: fatal error: ROOT/RDataFrame.hxx: No such file or directory
 #include "ROOT/RDataFrame.hxx"
                               ^
compilation terminated.
```
This probably needs to be checked against https://awesome-workshop.github.io/awesome-htautau-analysis/03-skimming/index.html

[UPDATE:]
- [ ] OK, reading forward, now I got it. However, I did instinctively test on local machine before starting to adding things to .`gitlab-ci.yml` and got stuck here because the compilation did not work.
Maybe add that this is expected to reduce the confusion...
- [ ] I would suggest to bring the compilation flag issue up to the beginning and start working on the .`gitlab-ci.yml` file only when the local compilation works. That would reflect the normal workflow.

**Comment by katilp** [comment]
10-eins-zwei-dry all fine, no comments

11-the-worlds-a-stage
- [x] I did not understand (before looking at the solution) how add `stages`,  as I was confused by the colon in front of the words in "another global parameter` :stages` (and the associated per-job parameter `:job:stage`." It is of course very clear after having seen the solution.

12-skim-milk, all fine no comments.

in 13-the-spy-game
- [x] I started trying on  `printf $SERVICE_PASS | base64 -d | kinit $CERN_USER` on lxplus and I got confused, and I was hesitant if I understood correctly as I do not get it working. Only after further reading I understood that these variables are to be set by me, and they should- if I got it right correspond to my login name and password. Maybe add at the beginning explicitly that this in not to be run locally but only in CI/CD through gitlab.
- [x] There are two variants suggested:   `printf $SERVICE_PASS | base64 -d | kinit $CERN_USER` earlier in the page and in the solution and `echo $SERVICE_PASS | kinit $CERN_USER` before the solution: are they meant to be different?
- [x] Adding the output file name in the script of skim_ggH somehoe escaped my attention. However, by now I've learnt to look at the output log of this stage of my CI/CD pipeline and found the error message there.

14-plotting-to-take-over-the-world, all fine, no comments

**Comment by kratsg** [comment]
> * [ ]  It would be useful to have a brief explanation of the scope of the listing (in YAML) below Scalars. Do I get it correctly that it is there to illustrate the syntax of different things in YAML? It would maybe be good to start with a typical example YAML file in the CI context.

this is covered in the next section. we try to just start with yaml first, before moving on to what it looks like for CI.

> [ ] I must be missing something, I pushed the (empty-as-instructed) file into the repo but I do not see what is in the instructions but this:

Updated to use `echo "hello world" >> .gitlab-ci.yml` instead of `touch`. Seems like an update to GitLab automatically stops it from running on empty CI files... ok.

> * [ ]  I would suggest to bring the compilation flag issue up to the beginning and start working on the .`gitlab-ci.yml` file only when the local compilation works. That would reflect the normal workflow.

That's not generally the workflow I teach. I'm trying to emphasize people to use the CI/CD logs to figure out what's going wrong. So if something goes wrong, they can debug locally however they like, but it's not what I want to cover.



> * [ ]  I did not understand (before looking at the solution) how add `stages`,  as I was confused by the colon in front of the words in "another global parameter` :stages` (and the associated per-job parameter `:job:stage`." It is of course very clear after having seen the solution.

This was covered in a callout in 04

```
> ## Understanding the Reference
>
> One will notice that the reference uses colons like `image:name` to refer to parameter names. This is represented in yaml like:
> ~~~
> job:
>   image:
>     name: rikorose/gcc-cmake:gcc-6
> ~~~
> {: .language-yaml}
> where the colon refers to a child key.
{: .callout}
```

and when I actively teach this, I repeatedly make a note because this is the grammar used for the GitLab CI/CD reference. I've gone ahead and copied that callout to this lesson as well to re-emphasize it for anyone going through on their own.
